# Generated by Django 6.1 on 2026-08-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerApp', '0001_initial'),
        ('JobApp', '0002_job_agreed_price_job_requested_date_job_service_and_more'),
        ('TailorApp', '0002_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='CustomerApp.customerprofile')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='JobApp.job')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='TailorApp.tailorprofile')),
            ],
        ),
    ]
