# Generated by Django 6.1 on 2026-08-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tailoring', 'Tailoring'), ('alteration', 'Clothing Alteration'), ('repair', 'Clothing Repair'), ('embroidery', 'Embroidery'), ('design', 'Clothing Design'), ('other', 'Other')], default='tailoring', max_length=30)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=150)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='job_references/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='CustomerApp.customerprofile')),
            ],
        ),
    ]
